spring:
  application:
    name: ApacheCamelIntegration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:8100/soarProject?currentSchema=public
    username: postgres
    password: Pooja@143
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


